local ui = loadstring(game:HttpGet("https://raw.githubusercontent.com/tammmmmm/github/main/%E6%B2%83%E5%88%A9%E5%9B%BE%E4%B9%A6%E9%A6%86.lua"))()
local mainUI = ui:Init(game:GetService("CoreGui"))
local soapTab = mainUI:AddTab("Tam's Teleports")
local teleportpart = soapTab:AddSection("Teleports")

local Armory = teleportpart:AddButton("Armory", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/tammmmmm/github/main/%E4%B8%BB%E4%BC%A0%E9%80%81.lua"))()
end)
local Criminal = teleportpart:AddButton("Crim Base", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tammmmmm/github/main/%E7%8C%A9%E7%BA%A2%E4%BC%A0%E9%80%81.lua"))()
end)
local Caf = teleportpart:AddButton("Cafeteria Knife", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tammmmmm/github/main/%E5%8E%A8%E6%88%BF.lua"))()
end)
local Yard = teleportpart:AddButton("Yard Knife", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tammmmmm/github/main/%E9%99%A2%E5%AD%90%E5%88%80.lua"))()
end)
local Lobby = teleportpart:AddButton("Lobby", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tammmmmm/github/main/%E5%A4%A7%E5%A0%82.lua"))()
end)
